name: Bits and pieces
url: http://blog.brunobonacci.com
author: Bruno Bonacci
description: Between bits and bytes and all other pieces.

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments
markdown: kramdown
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

gems: [jekyll-paginate]
