# Site settings
title: Bits and pieces
description: 'Between bits and bytes and all other pieces.<br/>A tech blog about Clojure, BigData, and Software Architecture.'
url: 'http://blog.brunobonacci.com/'
baseurl: '/'
google_analytics: 'UA-51571233-1'
disqus_shortname: 'bitsandpieces2'

author:
  name: 'Bruno Bonacci'
  email:
  twitter_username: BrunoBonacci
  facebook_username:
  github_username:  BrunoBonacci
  linkedin_username: brunobonacci

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 100
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
